//
// File generated by /usr/local/root_v5.34.21_enableall/bin/rootcint at Thu Jun 25 14:58:34 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME c14pulse_dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "c14pulse_dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void c14pulse_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_c14pulse(void *p = 0);
   static void *newArray_c14pulse(Long_t size, void *p);
   static void delete_c14pulse(void *p);
   static void deleteArray_c14pulse(void *p);
   static void destruct_c14pulse(void *p);
   static void streamer_c14pulse(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::c14pulse*)
   {
      ::c14pulse *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::c14pulse >(0);
      static ::ROOT::TGenericClassInfo 
         instance("c14pulse", ::c14pulse::Class_Version(), "./c14pulse.hh", 15,
                  typeid(::c14pulse), DefineBehavior(ptr, ptr),
                  &::c14pulse::Dictionary, isa_proxy, 0,
                  sizeof(::c14pulse) );
      instance.SetNew(&new_c14pulse);
      instance.SetNewArray(&newArray_c14pulse);
      instance.SetDelete(&delete_c14pulse);
      instance.SetDeleteArray(&deleteArray_c14pulse);
      instance.SetDestructor(&destruct_c14pulse);
      instance.SetStreamerFunc(&streamer_c14pulse);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::c14pulse*)
   {
      return GenerateInitInstanceLocal((::c14pulse*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::c14pulse*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
atomic_TClass_ptr c14pulse::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *c14pulse::Class_Name()
{
   return "c14pulse";
}

//______________________________________________________________________________
const char *c14pulse::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::c14pulse*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int c14pulse::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::c14pulse*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void c14pulse::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::c14pulse*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *c14pulse::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::c14pulse*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void c14pulse::Streamer(TBuffer &R__b)
{
   // Stream an object of class c14pulse.

   TObject::Streamer(R__b);
}

//______________________________________________________________________________
void c14pulse::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class c14pulse.
      TClass *R__cl = ::c14pulse::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "BGFraction", (void*)&BGFraction);
      R__insp.InspectMember("vector<double>", (void*)&BGFraction, "BGFraction.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MCinputdir", (void*)&MCinputdir);
      R__insp.InspectMember("string", (void*)&MCinputdir, "MCinputdir.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MCDataFile", (void*)&MCDataFile);
      R__insp.InspectMember("string", (void*)&MCDataFile, "MCDataFile.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Realinputdir", (void*)&Realinputdir);
      R__insp.InspectMember("string", (void*)&Realinputdir, "Realinputdir.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "RealDataFile", (void*)&RealDataFile);
      R__insp.InspectMember("string", (void*)&RealDataFile, "RealDataFile.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "outputdir", (void*)&outputdir);
      R__insp.InspectMember("string", (void*)&outputdir, "outputdir.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "c14_spectrum_endpoint", &c14_spectrum_endpoint);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "c14_spectrum_startpoint", &c14_spectrum_startpoint);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "c14_energy_spectrum", (void*)&c14_energy_spectrum);
      R__insp.InspectMember("vector<double>", (void*)&c14_energy_spectrum, "c14_energy_spectrum.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "c14_energy_spectrum_1st", (void*)&c14_energy_spectrum_1st);
      R__insp.InspectMember("vector<double>", (void*)&c14_energy_spectrum_1st, "c14_energy_spectrum_1st.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "c14_energy_spectrum_2nd", (void*)&c14_energy_spectrum_2nd);
      R__insp.InspectMember("vector<double>", (void*)&c14_energy_spectrum_2nd, "c14_energy_spectrum_2nd.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "c14_energy_spectrum_3rd", (void*)&c14_energy_spectrum_3rd);
      R__insp.InspectMember("vector<double>", (void*)&c14_energy_spectrum_3rd, "c14_energy_spectrum_3rd.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*EnergyMC", &EnergyMC);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*C14_EnergyMC_1st", &C14_EnergyMC_1st);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*C14_EnergyMC_2nd", &C14_EnergyMC_2nd);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*C14_EnergyMC_3rd", &C14_EnergyMC_3rd);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*C14_Quenching_Model", &C14_Quenching_Model);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*quenching_plot", &quenching_plot);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Histlist", &Histlist);
      R__insp.InspectMember(Histlist, "Histlist.");
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_c14pulse(void *p) {
      return  p ? new(p) ::c14pulse : new ::c14pulse;
   }
   static void *newArray_c14pulse(Long_t nElements, void *p) {
      return p ? new(p) ::c14pulse[nElements] : new ::c14pulse[nElements];
   }
   // Wrapper around operator delete
   static void delete_c14pulse(void *p) {
      delete ((::c14pulse*)p);
   }
   static void deleteArray_c14pulse(void *p) {
      delete [] ((::c14pulse*)p);
   }
   static void destruct_c14pulse(void *p) {
      typedef ::c14pulse current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_c14pulse(TBuffer &buf, void *obj) {
      ((::c14pulse*)obj)->::c14pulse::Streamer(buf);
   }
} // end of namespace ROOT for class ::c14pulse

/********************************************************
* c14pulse_dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablec14pulse_dict();

extern "C" void G__set_cpp_environmentc14pulse_dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("c14pulse.hh");
  G__cpp_reset_tagtablec14pulse_dict();
}
#include <new>
extern "C" int G__cpp_dllrevc14pulse_dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* c14pulse */
static int G__c14pulse_dict_605_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   c14pulse* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new c14pulse[n];
     } else {
       p = new((void*) gvp) c14pulse[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new c14pulse;
     } else {
       p = new((void*) gvp) c14pulse;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__c14pulse_dictLN_c14pulse));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((c14pulse*) G__getstructoffset())->Recon_DataAnalysis();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((c14pulse*) G__getstructoffset())->ODTree_DataAnalysis((int) G__int(libp->para[0]), (int) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((c14pulse*) G__getstructoffset())->Calculate_MCData((TTree*) G__int(libp->para[0]), (TH1F*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((c14pulse*) G__getstructoffset())->Readdatafile((TChain*) G__int(libp->para[0]), (int) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((c14pulse*) G__getstructoffset())->Readdatafile((TChain*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((c14pulse*) G__getstructoffset())->Calculate_Convolution((TH1F*) G__int(libp->para[0]), (TH1F*) G__int(libp->para[1])
, (TH1F*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((c14pulse*) G__getstructoffset())->Calculate_Norm((TH1F*) G__int(libp->para[0]), *(vector<double>*) libp->para[1].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((c14pulse*) G__getstructoffset())->scint_e_quenching((double) G__double(libp->para[0]), (double*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((c14pulse*) G__getstructoffset())->scint_e_quenching((double) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((c14pulse*) G__getstructoffset())->Scint_Quenching_Model((TTree*) G__int(libp->para[0]), (TH1F*) G__int(libp->para[1])
, (TH1F*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((c14pulse*) G__getstructoffset())->response_function((double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (double*) G__int(libp->para[2]), (int) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((c14pulse*) G__getstructoffset())->C14Fit((double*) G__int(libp->para[0]), (double*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((c14pulse*) G__getstructoffset())->C14Fit_1st((double*) G__int(libp->para[0]), (double*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((c14pulse*) G__getstructoffset())->C14Fit_2nd((double*) G__int(libp->para[0]), (double*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((c14pulse*) G__getstructoffset())->TotalFit((double*) G__int(libp->para[0]), (double*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TObjArray* pobj;
         TObjArray xobj = ((c14pulse*) G__getstructoffset())->GetHistArray();
         pobj = new TObjArray(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = ((c14pulse*) G__getstructoffset())->GetMCinputdir();
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((c14pulse*) G__getstructoffset())->SetMCinputdir(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = ((c14pulse*) G__getstructoffset())->GetMCDataFile();
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((c14pulse*) G__getstructoffset())->SetMCDataFile(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = ((c14pulse*) G__getstructoffset())->GetRealinputdir();
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((c14pulse*) G__getstructoffset())->SetRealinputdir(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = ((c14pulse*) G__getstructoffset())->GetRealDataFile();
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((c14pulse*) G__getstructoffset())->SetRealDataFile(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = ((c14pulse*) G__getstructoffset())->Getoutputdir();
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((c14pulse*) G__getstructoffset())->Setoutputdir(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<int>* pobj;
         vector<int> xobj = ((c14pulse*) G__getstructoffset())->Colors();
         pobj = new vector<int>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((c14pulse*) G__getstructoffset())->Isotope_Sum((int) G__int(libp->para[0]), (double*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((c14pulse*) G__getstructoffset())->Isotope_Fraction((int) G__int(libp->para[0]), (double*) G__int(libp->para[1])
, (double*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((c14pulse*) G__getstructoffset())->multicut((float) G__double(libp->para[0]), (float) G__double(libp->para[1])
, (float) G__double(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) c14pulse::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) c14pulse::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) c14pulse::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      c14pulse::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((c14pulse*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) c14pulse::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) c14pulse::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) c14pulse::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__c14pulse_dict_605_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) c14pulse::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef c14pulse G__Tc14pulse;
static int G__c14pulse_dict_605_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (c14pulse*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((c14pulse*) (soff+(sizeof(c14pulse)*i)))->~G__Tc14pulse();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (c14pulse*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((c14pulse*) (soff))->~G__Tc14pulse();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* c14pulse */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncc14pulse_dict {
 public:
  G__Sizep2memfuncc14pulse_dict(): p(&G__Sizep2memfuncc14pulse_dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncc14pulse_dict::*p)();
};

size_t G__get_sizep2memfuncc14pulse_dict()
{
  G__Sizep2memfuncc14pulse_dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancec14pulse_dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__c14pulse_dictLN_c14pulse))) {
     c14pulse *G__Lderived;
     G__Lderived=(c14pulse*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__c14pulse_dictLN_c14pulse),G__get_linked_tagnum(&G__c14pulse_dictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablec14pulse_dict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__c14pulse_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__c14pulse_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__c14pulse_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__c14pulse_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__c14pulse_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__c14pulse_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__c14pulse_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__c14pulse_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__c14pulse_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__c14pulse_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__c14pulse_dictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__c14pulse_dictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__c14pulse_dictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__c14pulse_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__c14pulse_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__c14pulse_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__c14pulse_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__c14pulse_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__c14pulse_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__c14pulse_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__c14pulse_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__c14pulse_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__c14pulse_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__c14pulse_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__c14pulse_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__c14pulse_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__c14pulse_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__c14pulse_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__c14pulse_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__c14pulse_dictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__c14pulse_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__c14pulse_dictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__c14pulse_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__c14pulse_dictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* c14pulse */
static void G__setup_memvarc14pulse(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__c14pulse_dictLN_c14pulse));
   { c14pulse *p; p=(c14pulse*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->BGFraction)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__c14pulse_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"BGFraction=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__c14pulse_dictLN_string),-1,-1,4,"MCinputdir=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__c14pulse_dictLN_string),-1,-1,4,"MCDataFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__c14pulse_dictLN_string),-1,-1,4,"Realinputdir=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__c14pulse_dictLN_string),-1,-1,4,"RealDataFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__c14pulse_dictLN_string),-1,-1,4,"outputdir=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"c14_spectrum_endpoint=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"c14_spectrum_startpoint=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__c14pulse_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"c14_energy_spectrum=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__c14pulse_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"c14_energy_spectrum_1st=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__c14pulse_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"c14_energy_spectrum_2nd=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__c14pulse_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"c14_energy_spectrum_3rd=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,2,0,G__get_linked_tagnum(&G__c14pulse_dictLN_TH1F),-1,-1,4,"EnergyMC=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__c14pulse_dictLN_TH1F),-1,-1,4,"C14_EnergyMC_1st=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__c14pulse_dictLN_TH1F),-1,-1,4,"C14_EnergyMC_2nd=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__c14pulse_dictLN_TH1F),-1,-1,4,"C14_EnergyMC_3rd=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__c14pulse_dictLN_TH1F),-1,-1,4,"C14_Quenching_Model=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__c14pulse_dictLN_TH1F),-1,-1,4,"quenching_plot=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__c14pulse_dictLN_TObjArray),-1,-1,4,"Histlist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__c14pulse_dictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarc14pulse_dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncc14pulse(void) {
   /* c14pulse */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__c14pulse_dictLN_c14pulse));
   G__memfunc_setup("c14pulse",753,G__c14pulse_dict_605_0_1, 105, G__get_linked_tagnum(&G__c14pulse_dictLN_c14pulse), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Recon_DataAnalysis",1812,G__c14pulse_dict_605_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ODTree_DataAnalysis",1856,G__c14pulse_dict_605_0_3, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - - i - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Calculate_MCData",1527,G__c14pulse_dict_605_0_4, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'TTree' - 0 - - U 'TH1F' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Readdatafile",1206,G__c14pulse_dict_605_0_5, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'TChain' - 0 - - i - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Readdatafile",1206,G__c14pulse_dict_605_0_6, 121, -1, -1, 0, 3, 1, 1, 0, 
"U 'TChain' - 0 - - i - - 0 - - "
"i - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Calculate_Convolution",2189,G__c14pulse_dict_605_0_7, 121, -1, -1, 0, 3, 1, 1, 0, 
"U 'TH1F' - 0 - - U 'TH1F' - 0 - - "
"U 'TH1F' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Calculate_Norm",1417,G__c14pulse_dict_605_0_8, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'TH1F' - 0 - - u 'vector<double,allocator<double> >' 'vector<double>' 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("scint_e_quenching",1798,G__c14pulse_dict_605_0_9, 100, -1, -1, 0, 2, 1, 1, 0, 
"d - - 0 - - D - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("scint_e_quenching",1798,G__c14pulse_dict_605_0_10, 100, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Scint_Quenching_Model",2130,G__c14pulse_dict_605_0_11, 121, -1, -1, 0, 3, 1, 1, 0, 
"U 'TTree' - 0 - - U 'TH1F' - 0 - - "
"U 'TH1F' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("response_function",1844,G__c14pulse_dict_605_0_12, 100, -1, -1, 0, 4, 1, 1, 0, 
"d - - 0 - - d - - 0 - - "
"D - - 0 - - i - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("C14Fit",459,G__c14pulse_dict_605_0_13, 100, -1, -1, 0, 2, 1, 1, 0, 
"D - - 0 - - D - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("C14Fit_1st",834,G__c14pulse_dict_605_0_14, 100, -1, -1, 0, 2, 1, 1, 0, 
"D - - 0 - - D - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("C14Fit_2nd",814,G__c14pulse_dict_605_0_15, 100, -1, -1, 0, 2, 1, 1, 0, 
"D - - 0 - - D - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TotalFit",807,G__c14pulse_dict_605_0_16, 100, -1, -1, 0, 2, 1, 1, 0, 
"D - - 0 - - D - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHistArray",1207,G__c14pulse_dict_605_0_17, 117, G__get_linked_tagnum(&G__c14pulse_dictLN_TObjArray), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMCinputdir",1311,G__c14pulse_dict_605_0_18, 117, G__get_linked_tagnum(&G__c14pulse_dictLN_string), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMCinputdir",1323,G__c14pulse_dict_605_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - val", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMCDataFile",1194,G__c14pulse_dict_605_0_20, 117, G__get_linked_tagnum(&G__c14pulse_dictLN_string), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMCDataFile",1206,G__c14pulse_dict_605_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - val", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetRealinputdir",1555,G__c14pulse_dict_605_0_22, 117, G__get_linked_tagnum(&G__c14pulse_dictLN_string), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetRealinputdir",1567,G__c14pulse_dict_605_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - val", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetRealDataFile",1438,G__c14pulse_dict_605_0_24, 117, G__get_linked_tagnum(&G__c14pulse_dictLN_string), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetRealDataFile",1450,G__c14pulse_dict_605_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - val", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Getoutputdir",1296,G__c14pulse_dict_605_0_26, 117, G__get_linked_tagnum(&G__c14pulse_dictLN_string), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Setoutputdir",1308,G__c14pulse_dict_605_0_27, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - val", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Colors",626,G__c14pulse_dict_605_0_28, 117, G__get_linked_tagnum(&G__c14pulse_dictLN_vectorlEintcOallocatorlEintgRsPgR), G__defined_typename("vector<int>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Isotope_Sum",1143,G__c14pulse_dict_605_0_29, 100, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - - D - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Isotope_Fraction",1656,G__c14pulse_dict_605_0_30, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - - D - - 0 - - "
"D - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("multicut",887,G__c14pulse_dict_605_0_31, 103, -1, -1, 0, 3, 1, 1, 0, 
"f - - 0 - - f - - 0 - - "
"f - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__c14pulse_dict_605_0_32, 85, G__get_linked_tagnum(&G__c14pulse_dictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&c14pulse::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__c14pulse_dict_605_0_33, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&c14pulse::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__c14pulse_dict_605_0_34, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&c14pulse::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__c14pulse_dict_605_0_35, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&c14pulse::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__c14pulse_dictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__c14pulse_dict_605_0_39, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__c14pulse_dict_605_0_40, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&c14pulse::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__c14pulse_dict_605_0_41, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&c14pulse::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__c14pulse_dict_605_0_42, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&c14pulse::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__c14pulse_dict_605_0_43, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&c14pulse::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~c14pulse", 879, G__c14pulse_dict_605_0_44, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncc14pulse_dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalc14pulse_dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcc14pulse_dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__c14pulse_dictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__c14pulse_dictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__c14pulse_dictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__c14pulse_dictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__c14pulse_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__c14pulse_dictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__c14pulse_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__c14pulse_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__c14pulse_dictLN_TObjArray = { "TObjArray" , 99 , -1 };
G__linked_taginfo G__c14pulse_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__c14pulse_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__c14pulse_dictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__c14pulse_dictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__c14pulse_dictLN_TH1F = { "TH1F" , 99 , -1 };
G__linked_taginfo G__c14pulse_dictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__c14pulse_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__c14pulse_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__c14pulse_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__c14pulse_dictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__c14pulse_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__c14pulse_dictLN_TChain = { "TChain" , 99 , -1 };
G__linked_taginfo G__c14pulse_dictLN_c14pulse = { "c14pulse" , 99 , -1 };
G__linked_taginfo G__c14pulse_dictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__c14pulse_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablec14pulse_dict() {
  G__c14pulse_dictLN_TClass.tagnum = -1 ;
  G__c14pulse_dictLN_TBuffer.tagnum = -1 ;
  G__c14pulse_dictLN_TMemberInspector.tagnum = -1 ;
  G__c14pulse_dictLN_TObject.tagnum = -1 ;
  G__c14pulse_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__c14pulse_dictLN_string.tagnum = -1 ;
  G__c14pulse_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__c14pulse_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__c14pulse_dictLN_TObjArray.tagnum = -1 ;
  G__c14pulse_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__c14pulse_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__c14pulse_dictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__c14pulse_dictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__c14pulse_dictLN_TH1F.tagnum = -1 ;
  G__c14pulse_dictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__c14pulse_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__c14pulse_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__c14pulse_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__c14pulse_dictLN_TTree.tagnum = -1 ;
  G__c14pulse_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__c14pulse_dictLN_TChain.tagnum = -1 ;
  G__c14pulse_dictLN_c14pulse.tagnum = -1 ;
  G__c14pulse_dictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__c14pulse_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablec14pulse_dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__c14pulse_dictLN_TClass);
   G__get_linked_tagnum_fwd(&G__c14pulse_dictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__c14pulse_dictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__c14pulse_dictLN_TObject);
   G__get_linked_tagnum_fwd(&G__c14pulse_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__c14pulse_dictLN_string);
   G__get_linked_tagnum_fwd(&G__c14pulse_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__c14pulse_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__c14pulse_dictLN_TObjArray);
   G__get_linked_tagnum_fwd(&G__c14pulse_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__c14pulse_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__c14pulse_dictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__c14pulse_dictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__c14pulse_dictLN_TH1F);
   G__get_linked_tagnum_fwd(&G__c14pulse_dictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__c14pulse_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__c14pulse_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__c14pulse_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__c14pulse_dictLN_TTree);
   G__get_linked_tagnum_fwd(&G__c14pulse_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__c14pulse_dictLN_TChain);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__c14pulse_dictLN_c14pulse),sizeof(c14pulse),-1,29952,(char*)NULL,G__setup_memvarc14pulse,G__setup_memfuncc14pulse);
   G__get_linked_tagnum_fwd(&G__c14pulse_dictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__c14pulse_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupc14pulse_dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupc14pulse_dict()");
  G__set_cpp_environmentc14pulse_dict();
  G__cpp_setup_tagtablec14pulse_dict();

  G__cpp_setup_inheritancec14pulse_dict();

  G__cpp_setup_typetablec14pulse_dict();

  G__cpp_setup_memvarc14pulse_dict();

  G__cpp_setup_memfuncc14pulse_dict();
  G__cpp_setup_globalc14pulse_dict();
  G__cpp_setup_funcc14pulse_dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncc14pulse_dict();
  return;
}
class G__cpp_setup_initc14pulse_dict {
  public:
    G__cpp_setup_initc14pulse_dict() { G__add_setup_func("c14pulse_dict",(G__incsetup)(&G__cpp_setupc14pulse_dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initc14pulse_dict() { G__remove_setup_func("c14pulse_dict"); }
};
G__cpp_setup_initc14pulse_dict G__cpp_setup_initializerc14pulse_dict;

