/********************************************************************
* c14pulse_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error c14pulse_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablec14pulse_dict();
extern void G__cpp_setup_inheritancec14pulse_dict();
extern void G__cpp_setup_typetablec14pulse_dict();
extern void G__cpp_setup_memvarc14pulse_dict();
extern void G__cpp_setup_globalc14pulse_dict();
extern void G__cpp_setup_memfuncc14pulse_dict();
extern void G__cpp_setup_funcc14pulse_dict();
extern void G__set_cpp_environmentc14pulse_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "c14pulse.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__c14pulse_dictLN_TClass;
extern G__linked_taginfo G__c14pulse_dictLN_TBuffer;
extern G__linked_taginfo G__c14pulse_dictLN_TMemberInspector;
extern G__linked_taginfo G__c14pulse_dictLN_TObject;
extern G__linked_taginfo G__c14pulse_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__c14pulse_dictLN_string;
extern G__linked_taginfo G__c14pulse_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__c14pulse_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__c14pulse_dictLN_TObjArray;
extern G__linked_taginfo G__c14pulse_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__c14pulse_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__c14pulse_dictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__c14pulse_dictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__c14pulse_dictLN_TH1F;
extern G__linked_taginfo G__c14pulse_dictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__c14pulse_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__c14pulse_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__c14pulse_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__c14pulse_dictLN_TTree;
extern G__linked_taginfo G__c14pulse_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__c14pulse_dictLN_TChain;
extern G__linked_taginfo G__c14pulse_dictLN_c14pulse;
extern G__linked_taginfo G__c14pulse_dictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__c14pulse_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
