/********************************************************************
* vetopulsesplit_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error vetopulsesplit_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablevetopulsesplit_dict();
extern void G__cpp_setup_inheritancevetopulsesplit_dict();
extern void G__cpp_setup_typetablevetopulsesplit_dict();
extern void G__cpp_setup_memvarvetopulsesplit_dict();
extern void G__cpp_setup_globalvetopulsesplit_dict();
extern void G__cpp_setup_memfuncvetopulsesplit_dict();
extern void G__cpp_setup_funcvetopulsesplit_dict();
extern void G__set_cpp_environmentvetopulsesplit_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "vetopulsesplit.hh"
#include "odselector/odselector.h"
#include "DSTtreeSelector/DSTtreeSelector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__vetopulsesplit_dictLN_TClass;
extern G__linked_taginfo G__vetopulsesplit_dictLN_TBuffer;
extern G__linked_taginfo G__vetopulsesplit_dictLN_TMemberInspector;
extern G__linked_taginfo G__vetopulsesplit_dictLN_TObject;
extern G__linked_taginfo G__vetopulsesplit_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__vetopulsesplit_dictLN_string;
extern G__linked_taginfo G__vetopulsesplit_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__vetopulsesplit_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__vetopulsesplit_dictLN_TList;
extern G__linked_taginfo G__vetopulsesplit_dictLN_TObjArray;
extern G__linked_taginfo G__vetopulsesplit_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__vetopulsesplit_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__vetopulsesplit_dictLN_TArrayF;
extern G__linked_taginfo G__vetopulsesplit_dictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__vetopulsesplit_dictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__vetopulsesplit_dictLN_TH1F;
extern G__linked_taginfo G__vetopulsesplit_dictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__vetopulsesplit_dictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__vetopulsesplit_dictLN_TH2F;
extern G__linked_taginfo G__vetopulsesplit_dictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__vetopulsesplit_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__vetopulsesplit_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__vetopulsesplit_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__vetopulsesplit_dictLN_TTree;
extern G__linked_taginfo G__vetopulsesplit_dictLN_TFile;
extern G__linked_taginfo G__vetopulsesplit_dictLN_TBranch;
extern G__linked_taginfo G__vetopulsesplit_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__vetopulsesplit_dictLN_TSelector;
extern G__linked_taginfo G__vetopulsesplit_dictLN_TChain;
extern G__linked_taginfo G__vetopulsesplit_dictLN_TNtuple;
extern G__linked_taginfo G__vetopulsesplit_dictLN_vetopulsesplit;
extern G__linked_taginfo G__vetopulsesplit_dictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__vetopulsesplit_dictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__vetopulsesplit_dictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__vetopulsesplit_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__vetopulsesplit_dictLN_vectorlETH1FmUcOallocatorlETH1FmUgRsPgR;
extern G__linked_taginfo G__vetopulsesplit_dictLN_reverse_iteratorlEvectorlETH1FmUcOallocatorlETH1FmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__vetopulsesplit_dictLN_vectorlETH2FmUcOallocatorlETH2FmUgRsPgR;
extern G__linked_taginfo G__vetopulsesplit_dictLN_reverse_iteratorlEvectorlETH2FmUcOallocatorlETH2FmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__vetopulsesplit_dictLN_odselector;
extern G__linked_taginfo G__vetopulsesplit_dictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR;
extern G__linked_taginfo G__vetopulsesplit_dictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__vetopulsesplit_dictLN_TProofOutputFile;
extern G__linked_taginfo G__vetopulsesplit_dictLN_DSTtreeSelector;

/* STUB derived class for protected member access */
