/********************************************************************
* reconSelector_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error reconSelector_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablereconSelector_dict();
extern void G__cpp_setup_inheritancereconSelector_dict();
extern void G__cpp_setup_typetablereconSelector_dict();
extern void G__cpp_setup_memvarreconSelector_dict();
extern void G__cpp_setup_globalreconSelector_dict();
extern void G__cpp_setup_memfuncreconSelector_dict();
extern void G__cpp_setup_funcreconSelector_dict();
extern void G__set_cpp_environmentreconSelector_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "reconSelector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__reconSelector_dictLN_TClass;
extern G__linked_taginfo G__reconSelector_dictLN_TBuffer;
extern G__linked_taginfo G__reconSelector_dictLN_TMemberInspector;
extern G__linked_taginfo G__reconSelector_dictLN_TObject;
extern G__linked_taginfo G__reconSelector_dictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__reconSelector_dictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__reconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__reconSelector_dictLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__reconSelector_dictLN_string;
extern G__linked_taginfo G__reconSelector_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__reconSelector_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__reconSelector_dictLN_TList;
extern G__linked_taginfo G__reconSelector_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__reconSelector_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__reconSelector_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__reconSelector_dictLN_TFile;
extern G__linked_taginfo G__reconSelector_dictLN_TTree;
extern G__linked_taginfo G__reconSelector_dictLN_TBranch;
extern G__linked_taginfo G__reconSelector_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__reconSelector_dictLN_TSelector;
extern G__linked_taginfo G__reconSelector_dictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__reconSelector_dictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__reconSelector_dictLN_TProofOutputFile;
extern G__linked_taginfo G__reconSelector_dictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__reconSelector_dictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__reconSelector_dictLN_G4DSHitData;
extern G__linked_taginfo G__reconSelector_dictLN_ReconEvent;
extern G__linked_taginfo G__reconSelector_dictLN_TRint;
extern G__linked_taginfo G__reconSelector_dictLN_reconSelector;
extern G__linked_taginfo G__reconSelector_dictLN_vectorlEReconEventcOallocatorlEReconEventgRsPgR;
extern G__linked_taginfo G__reconSelector_dictLN_reverse_iteratorlEvectorlEReconEventcOallocatorlEReconEventgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__reconSelector_dictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__reconSelector_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
