//
// File generated by /usr/local/root_v5.34.21_enableall/bin/rootcint at Thu Jun 25 21:34:22 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME reconSelector_dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "reconSelector_dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void reconSelector_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_reconSelector(void *p = 0);
   static void *newArray_reconSelector(Long_t size, void *p);
   static void delete_reconSelector(void *p);
   static void deleteArray_reconSelector(void *p);
   static void destruct_reconSelector(void *p);
   static void streamer_reconSelector(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::reconSelector*)
   {
      ::reconSelector *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::reconSelector >(0);
      static ::ROOT::TGenericClassInfo 
         instance("reconSelector", ::reconSelector::Class_Version(), "./reconSelector.h", 30,
                  typeid(::reconSelector), DefineBehavior(ptr, ptr),
                  &::reconSelector::Dictionary, isa_proxy, 0,
                  sizeof(::reconSelector) );
      instance.SetNew(&new_reconSelector);
      instance.SetNewArray(&newArray_reconSelector);
      instance.SetDelete(&delete_reconSelector);
      instance.SetDeleteArray(&deleteArray_reconSelector);
      instance.SetDestructor(&destruct_reconSelector);
      instance.SetStreamerFunc(&streamer_reconSelector);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::reconSelector*)
   {
      return GenerateInitInstanceLocal((::reconSelector*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::reconSelector*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
atomic_TClass_ptr reconSelector::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *reconSelector::Class_Name()
{
   return "reconSelector";
}

//______________________________________________________________________________
const char *reconSelector::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::reconSelector*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int reconSelector::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::reconSelector*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void reconSelector::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::reconSelector*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *reconSelector::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::reconSelector*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void reconSelector::Streamer(TBuffer &R__b)
{
   // Stream an object of class reconSelector.

   TSelector::Streamer(R__b);
}

//______________________________________________________________________________
void reconSelector::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class reconSelector.
      TClass *R__cl = ::reconSelector::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "currentHit", (void*)&currentHit);
      R__insp.InspectMember("G4DSHitData", (void*)&currentHit, "currentHit.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "recon_evts", (void*)&recon_evts);
      R__insp.InspectMember("vector<ReconEvent>", (void*)&recon_evts, "recon_evts.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fChain", &fChain);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ev", &ev);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pdg", &pdg);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ene0", &ene0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "s1ene", &s1ene);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "s2ene", &s2ene);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "veto_visene", &veto_visene);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mu_visene", &mu_visene);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tpcene", &tpcene);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "vetoene", &vetoene);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "muene", &muene);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ene", &ene);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "npeS1", &npeS1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "npeS2", &npeS2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "npe", &npe);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "munpe", &munpe);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "vnpe", &vnpe);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nph", &nph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ndaughters", &ndaughters);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ndeposits", &ndeposits);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dep_pdg[10493]", dep_pdg);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dep_mat[10493]", dep_mat);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dep_track[10493]", dep_track);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dep_time[10493]", dep_time);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dep_ene[10493]", dep_ene);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dep_step[10493]", dep_step);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dep_x[10493]", dep_x);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dep_y[10493]", dep_y);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dep_z[10493]", dep_z);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dep_r[10493]", dep_r);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pe_time[1]", pe_time);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pe_pmt[1]", pe_pmt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "vpe_time[1]", vpe_time);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "vpe_pmt[1]", vpe_pmt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mupe_time[1]", mupe_time);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mupe_pmt[1]", mupe_pmt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ph_volume[1]", ph_volume);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ph_pid[1]", ph_pid);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ph_wl[1]", ph_wl);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ph_x[1]", ph_x);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ph_y[1]", ph_y);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ph_z[1]", ph_z);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ph_time[1]", ph_time);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ev", &b_ev);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_pdg", &b_pdg);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ene0", &b_ene0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_s1ene", &b_s1ene);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_s2ene", &b_s2ene);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_veto_visene", &b_veto_visene);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_mu_visene", &b_mu_visene);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_tpcene", &b_tpcene);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_vetoene", &b_vetoene);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_muene", &b_muene);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ene", &b_ene);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_npeS1", &b_npeS1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_npeS2", &b_npeS2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_npe", &b_npe);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_munpe", &b_munpe);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_vnpe", &b_vnpe);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_nph", &b_nph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ndaughters", &b_ndaughters);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ndeposits", &b_ndeposits);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dep_pdg", &b_dep_pdg);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dep_mat", &b_dep_mat);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dep_track", &b_dep_track);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dep_time", &b_dep_time);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dep_ene", &b_dep_ene);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dep_step", &b_dep_step);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dep_x", &b_dep_x);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dep_y", &b_dep_y);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dep_z", &b_dep_z);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_dep_r", &b_dep_r);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_pe_time", &b_pe_time);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_pe_pmt", &b_pe_pmt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_vpe_time", &b_vpe_time);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_vpe_pmt", &b_vpe_pmt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_mupe_time", &b_mupe_time);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_mupe_pmt", &b_mupe_pmt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ph_volume", &b_ph_volume);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ph_pid", &b_ph_pid);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ph_wl", &b_ph_wl);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ph_x", &b_ph_x);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ph_y", &b_ph_y);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ph_z", &b_ph_z);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_ph_time", &b_ph_time);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "event_id", &event_id);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "n_active", &n_active);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*recon_et", &recon_et);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*recon_ex", &recon_ex);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*recon_ey", &recon_ey);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*recon_ez", &recon_ez);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*recon_dt", &recon_dt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*recon_dz", &recon_dz);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*recon_dr", &recon_dr);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*recon_edep", &recon_edep);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*recon_eqch", &recon_eqch);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*recon_edep_electron", &recon_edep_electron);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*recon_edep_nuclear", &recon_edep_nuclear);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*recon_quenchingfactor", &recon_quenchingfactor);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*recon_parent_enrg", &recon_parent_enrg);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*recon_vol", &recon_vol);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*recon_particle", &recon_particle);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*recon_parent_pdg", &recon_parent_pdg);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*recon_contain_alpha", &recon_contain_alpha);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "event_pdg", &event_pdg);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "event_broken", &event_broken);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fRint", &fRint);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*ReconTree", &ReconTree);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fFile", &fFile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fProofFile", &fProofFile);
      TSelector::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_reconSelector(void *p) {
      return  p ? new(p) ::reconSelector : new ::reconSelector;
   }
   static void *newArray_reconSelector(Long_t nElements, void *p) {
      return p ? new(p) ::reconSelector[nElements] : new ::reconSelector[nElements];
   }
   // Wrapper around operator delete
   static void delete_reconSelector(void *p) {
      delete ((::reconSelector*)p);
   }
   static void deleteArray_reconSelector(void *p) {
      delete [] ((::reconSelector*)p);
   }
   static void destruct_reconSelector(void *p) {
      typedef ::reconSelector current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_reconSelector(TBuffer &buf, void *obj) {
      ((::reconSelector*)obj)->::reconSelector::Streamer(buf);
   }
} // end of namespace ROOT for class ::reconSelector

/********************************************************
* reconSelector_dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablereconSelector_dict();

extern "C" void G__set_cpp_environmentreconSelector_dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("reconSelector.h");
  G__cpp_reset_tagtablereconSelector_dict();
}
#include <new>
extern "C" int G__cpp_dllrevreconSelector_dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* reconSelector */
static int G__reconSelector_dict_610_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   reconSelector* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new reconSelector((TTree*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) reconSelector((TTree*) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new reconSelector[n];
       } else {
         p = new((void*) gvp) reconSelector[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new reconSelector;
       } else {
         p = new((void*) gvp) reconSelector;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__reconSelector_dictLN_reconSelector));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__reconSelector_dict_610_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((reconSelector*) G__getstructoffset())->SetTRint((TRint*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__reconSelector_dict_610_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) reconSelector::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__reconSelector_dict_610_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) reconSelector::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__reconSelector_dict_610_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) reconSelector::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__reconSelector_dict_610_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      reconSelector::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__reconSelector_dict_610_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((reconSelector*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__reconSelector_dict_610_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) reconSelector::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__reconSelector_dict_610_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) reconSelector::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__reconSelector_dict_610_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) reconSelector::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__reconSelector_dict_610_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) reconSelector::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef reconSelector G__TreconSelector;
static int G__reconSelector_dict_610_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (reconSelector*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((reconSelector*) (soff+(sizeof(reconSelector)*i)))->~G__TreconSelector();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (reconSelector*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((reconSelector*) (soff))->~G__TreconSelector();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* reconSelector */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncreconSelector_dict {
 public:
  G__Sizep2memfuncreconSelector_dict(): p(&G__Sizep2memfuncreconSelector_dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncreconSelector_dict::*p)();
};

size_t G__get_sizep2memfuncreconSelector_dict()
{
  G__Sizep2memfuncreconSelector_dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancereconSelector_dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__reconSelector_dictLN_reconSelector))) {
     reconSelector *G__Lderived;
     G__Lderived=(reconSelector*)0x1000;
     {
       TSelector *G__Lpbase=(TSelector*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__reconSelector_dictLN_reconSelector),G__get_linked_tagnum(&G__reconSelector_dictLN_TSelector),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__reconSelector_dictLN_reconSelector),G__get_linked_tagnum(&G__reconSelector_dictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablereconSelector_dict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__reconSelector_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Double_t>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Float_t>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::string>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ReconEvent>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEReconEventcOallocatorlEReconEventgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_reverse_iteratorlEvectorlEReconEventcOallocatorlEReconEventgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEReconEventcOallocatorlEReconEventgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_reverse_iteratorlEvectorlEReconEventcOallocatorlEReconEventgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEReconEventcOallocatorlEReconEventgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__reconSelector_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* reconSelector */
static void G__setup_memvarreconSelector(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__reconSelector_dictLN_reconSelector));
   { reconSelector *p; p=(reconSelector*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->currentHit)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_G4DSHitData),-1,-1,1,"currentHit=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->recon_evts)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEReconEventcOallocatorlEReconEventgRsPgR),G__defined_typename("vector<ReconEvent>"),-1,1,"recon_evts=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fChain)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TTree),-1,-1,1,"fChain=",0,"!pointer to the analyzed TTree or TChain");
   G__memvar_setup((void*)((long)(&p->ev)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ev=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pdg)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"pdg=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ene0)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"ene0=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->s1ene)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"s1ene=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->s2ene)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"s2ene=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->veto_visene)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"veto_visene=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mu_visene)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"mu_visene=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tpcene)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"tpcene=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->vetoene)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"vetoene=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->muene)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"muene=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ene)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"ene=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->npeS1)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"npeS1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->npeS2)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"npeS2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->npe)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"npe=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->munpe)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"munpe=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->vnpe)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"vnpe=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nph)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"nph=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ndaughters)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ndaughters=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ndeposits)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ndeposits=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dep_pdg)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"dep_pdg[10493]=",0,"[ndeposits]");
   G__memvar_setup((void*)((long)(&p->dep_mat)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"dep_mat[10493]=",0,"[ndeposits]");
   G__memvar_setup((void*)((long)(&p->dep_track)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"dep_track[10493]=",0,"[ndeposits]");
   G__memvar_setup((void*)((long)(&p->dep_time)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"dep_time[10493]=",0,"[ndeposits]");
   G__memvar_setup((void*)((long)(&p->dep_ene)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dep_ene[10493]=",0,"[ndeposits]");
   G__memvar_setup((void*)((long)(&p->dep_step)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dep_step[10493]=",0,"[ndeposits]");
   G__memvar_setup((void*)((long)(&p->dep_x)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dep_x[10493]=",0,"[ndeposits]");
   G__memvar_setup((void*)((long)(&p->dep_y)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dep_y[10493]=",0,"[ndeposits]");
   G__memvar_setup((void*)((long)(&p->dep_z)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dep_z[10493]=",0,"[ndeposits]");
   G__memvar_setup((void*)((long)(&p->dep_r)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"dep_r[10493]=",0,"[ndeposits]");
   G__memvar_setup((void*)((long)(&p->pe_time)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"pe_time[1]=",0,"[npe]");
   G__memvar_setup((void*)((long)(&p->pe_pmt)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"pe_pmt[1]=",0,"[npe]");
   G__memvar_setup((void*)((long)(&p->vpe_time)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"vpe_time[1]=",0,"[vnpe]");
   G__memvar_setup((void*)((long)(&p->vpe_pmt)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"vpe_pmt[1]=",0,"[vnpe]");
   G__memvar_setup((void*)((long)(&p->mupe_time)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"mupe_time[1]=",0,"[munpe]");
   G__memvar_setup((void*)((long)(&p->mupe_pmt)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"mupe_pmt[1]=",0,"[munpe]");
   G__memvar_setup((void*)((long)(&p->ph_volume)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ph_volume[1]=",0,"[nph]");
   G__memvar_setup((void*)((long)(&p->ph_pid)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ph_pid[1]=",0,"[nph]");
   G__memvar_setup((void*)((long)(&p->ph_wl)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"ph_wl[1]=",0,"[nph]");
   G__memvar_setup((void*)((long)(&p->ph_x)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"ph_x[1]=",0,"[nph]");
   G__memvar_setup((void*)((long)(&p->ph_y)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"ph_y[1]=",0,"[nph]");
   G__memvar_setup((void*)((long)(&p->ph_z)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"ph_z[1]=",0,"[nph]");
   G__memvar_setup((void*)((long)(&p->ph_time)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"ph_time[1]=",0,"[nph]");
   G__memvar_setup((void*)((long)(&p->b_ev)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_ev=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_pdg)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_pdg=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ene0)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_ene0=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_s1ene)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_s1ene=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_s2ene)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_s2ene=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_veto_visene)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_veto_visene=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_mu_visene)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_mu_visene=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_tpcene)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_tpcene=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_vetoene)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_vetoene=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_muene)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_muene=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ene)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_ene=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_npeS1)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_npeS1=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_npeS2)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_npeS2=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_npe)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_npe=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_munpe)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_munpe=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_vnpe)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_vnpe=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_nph)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_nph=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ndaughters)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_ndaughters=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ndeposits)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_ndeposits=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dep_pdg)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_dep_pdg=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dep_mat)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_dep_mat=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dep_track)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_dep_track=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dep_time)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_dep_time=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dep_ene)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_dep_ene=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dep_step)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_dep_step=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dep_x)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_dep_x=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dep_y)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_dep_y=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dep_z)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_dep_z=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_dep_r)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_dep_r=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_pe_time)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_pe_time=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_pe_pmt)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_pe_pmt=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_vpe_time)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_vpe_time=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_vpe_pmt)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_vpe_pmt=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_mupe_time)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_mupe_time=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_mupe_pmt)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_mupe_pmt=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ph_volume)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_ph_volume=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ph_pid)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_ph_pid=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ph_wl)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_ph_wl=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ph_x)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_ph_x=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ph_y)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_ph_y=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ph_z)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_ph_z=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_ph_time)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TBranch),-1,-1,1,"b_ph_time=",0,"!");
   G__memvar_setup((void*)((long)(&p->event_id)-(long)(p)),105,0,0,-1,-1,-1,1,"event_id=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->n_active)-(long)(p)),105,0,0,-1,-1,-1,1,"n_active=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->recon_et)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"recon_et=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->recon_ex)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"recon_ex=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->recon_ey)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"recon_ey=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->recon_ez)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"recon_ez=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->recon_dt)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"recon_dt=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->recon_dz)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"recon_dz=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->recon_dr)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"recon_dr=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->recon_edep)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"recon_edep=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->recon_eqch)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"recon_eqch=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->recon_edep_electron)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"recon_edep_electron=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->recon_edep_nuclear)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"recon_edep_nuclear=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->recon_quenchingfactor)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"recon_quenchingfactor=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->recon_parent_enrg)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"recon_parent_enrg=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->recon_vol)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlETStringcOallocatorlETStringgRsPgR),G__defined_typename("vector<TString>"),-1,1,"recon_vol=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->recon_particle)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlETStringcOallocatorlETStringgRsPgR),G__defined_typename("vector<TString>"),-1,1,"recon_particle=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->recon_parent_pdg)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,1,"recon_parent_pdg=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->recon_contain_alpha)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_vectorlEboolcOallocatorlEboolgRsPgR),G__defined_typename("vector<bool>"),-1,1,"recon_contain_alpha=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->event_pdg)-(long)(p)),105,0,0,-1,-1,-1,1,"event_pdg=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->event_broken)-(long)(p)),103,0,0,-1,-1,-1,1,"event_broken=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TRint),-1,-1,4,"fRint=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TTree),-1,-1,4,"ReconTree=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TFile),-1,-1,4,"fFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TProofOutputFile),-1,-1,4,"fProofFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__reconSelector_dictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarreconSelector_dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncreconSelector(void) {
   /* reconSelector */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__reconSelector_dictLN_reconSelector));
   G__memfunc_setup("reconSelector",1368,G__reconSelector_dict_610_0_1, 105, G__get_linked_tagnum(&G__reconSelector_dictLN_reconSelector), -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 '0' -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Version",742,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Begin",485,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SlaveBegin",992,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Notify",633,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Process",735,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetEntry",818,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 0, 
"n - 'Long64_t' 0 - entry i - 'Int_t' 0 '0' getall", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetOption",933,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetObject",899,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TObject' - 0 - obj", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetInputList",1240,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TList' - 0 - input", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetOutputList",1357,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__reconSelector_dictLN_TList), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SlaveTerminate",1444,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Terminate",937,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetTRint",797,G__reconSelector_dict_610_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TRint' - 0 - rint", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetOutputTree",1357,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "U 'TFile' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InitializeRE",1193,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 3, 1, 4, 0, 
"u 'ReconEvent' - 1 - - u 'G4DSHitData' - 1 - - "
"i - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CompatibleRE",1175,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 2, 1, 4, 0, 
"u 'ReconEvent' - 0 - - u 'ReconEvent' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MergeRE",647,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 2, 1, 4, 0, 
"u 'ReconEvent' - 1 - - u 'ReconEvent' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_point",969,(G__InterfaceMethod) NULL, 100, -1, -1, 0, 3, 1, 4, 0, 
"u 'vector<double,allocator<double> >' 'vector<double>' 0 - - u 'vector<double,allocator<double> >' 'vector<double>' 0 - - "
"d - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_point",969,(G__InterfaceMethod) NULL, 100, -1, -1, 0, 4, 1, 4, 0, 
"D - - 0 - - D - - 0 - - "
"d - - 0 - - i - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("o_scint_e_quenching",2004,(G__InterfaceMethod) NULL, 100, -1, -1, 0, 1, 1, 4, 0, "d - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_quenching_factor_organic_scintillator",4344,(G__InterfaceMethod) NULL, 100, -1, -1, 0, 1, 1, 4, 0, "u 'ReconEvent' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_quenching_factor_liquid_argon",3484,(G__InterfaceMethod) NULL, 100, -1, -1, 0, 2, 1, 4, 0, 
"u 'ReconEvent' - 0 - - g - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_quenching_factor",2111,(G__InterfaceMethod) NULL, 100, -1, -1, 0, 2, 1, 4, 0, 
"u 'ReconEvent' - 0 - - g - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("convertPDG",988,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__reconSelector_dictLN_string), -1, 0, 1, 1, 4, 0, "i - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("checkActive",1114,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 2, 1, 4, 0, 
"f - 'Float_t' 0 - - f - 'Float_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("convertVolume",1401,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__reconSelector_dictLN_string), -1, 0, 3, 1, 4, 0, 
"i - - 0 - - f - 'Float_t' 0 - - "
"f - 'Float_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("returnType",1090,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__reconSelector_dictLN_string), -1, 0, 1, 1, 4, 0, "i - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FillHistograms",1448,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "n - 'Long64_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TestFill",807,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "n - 'Long64_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EmptyHit",820,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "u 'G4DSHitData' - 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("returnHit",965,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "u 'G4DSHitData' - 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__reconSelector_dict_610_0_34, 85, G__get_linked_tagnum(&G__reconSelector_dictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&reconSelector::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__reconSelector_dict_610_0_35, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&reconSelector::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__reconSelector_dict_610_0_36, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&reconSelector::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__reconSelector_dict_610_0_37, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&reconSelector::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__reconSelector_dictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__reconSelector_dict_610_0_41, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__reconSelector_dict_610_0_42, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&reconSelector::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__reconSelector_dict_610_0_43, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&reconSelector::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__reconSelector_dict_610_0_44, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&reconSelector::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__reconSelector_dict_610_0_45, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&reconSelector::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~reconSelector", 1494, G__reconSelector_dict_610_0_46, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncreconSelector_dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalreconSelector_dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcreconSelector_dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__reconSelector_dictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_vectorlEfloatcOallocatorlEfloatgRsPgR = { "vector<float,allocator<float> >" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_vectorlEboolcOallocatorlEboolgRsPgR = { "vector<bool,allocator<bool> >" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__reconSelector_dictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_TBranch = { "TBranch" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_TSelector = { "TSelector" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_TProofOutputFile = { "TProofOutputFile" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_G4DSHitData = { "G4DSHitData" , 115 , -1 };
G__linked_taginfo G__reconSelector_dictLN_ReconEvent = { "ReconEvent" , 115 , -1 };
G__linked_taginfo G__reconSelector_dictLN_TRint = { "TRint" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_reconSelector = { "reconSelector" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_vectorlEReconEventcOallocatorlEReconEventgRsPgR = { "vector<ReconEvent,allocator<ReconEvent> >" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_reverse_iteratorlEvectorlEReconEventcOallocatorlEReconEventgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ReconEvent,allocator<ReconEvent> >::iterator>" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__reconSelector_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablereconSelector_dict() {
  G__reconSelector_dictLN_TClass.tagnum = -1 ;
  G__reconSelector_dictLN_TBuffer.tagnum = -1 ;
  G__reconSelector_dictLN_TMemberInspector.tagnum = -1 ;
  G__reconSelector_dictLN_TObject.tagnum = -1 ;
  G__reconSelector_dictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__reconSelector_dictLN_vectorlEfloatcOallocatorlEfloatgRsPgR.tagnum = -1 ;
  G__reconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__reconSelector_dictLN_vectorlEboolcOallocatorlEboolgRsPgR.tagnum = -1 ;
  G__reconSelector_dictLN_string.tagnum = -1 ;
  G__reconSelector_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__reconSelector_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__reconSelector_dictLN_TList.tagnum = -1 ;
  G__reconSelector_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__reconSelector_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__reconSelector_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__reconSelector_dictLN_TFile.tagnum = -1 ;
  G__reconSelector_dictLN_TTree.tagnum = -1 ;
  G__reconSelector_dictLN_TBranch.tagnum = -1 ;
  G__reconSelector_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__reconSelector_dictLN_TSelector.tagnum = -1 ;
  G__reconSelector_dictLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__reconSelector_dictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__reconSelector_dictLN_TProofOutputFile.tagnum = -1 ;
  G__reconSelector_dictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__reconSelector_dictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__reconSelector_dictLN_G4DSHitData.tagnum = -1 ;
  G__reconSelector_dictLN_ReconEvent.tagnum = -1 ;
  G__reconSelector_dictLN_TRint.tagnum = -1 ;
  G__reconSelector_dictLN_reconSelector.tagnum = -1 ;
  G__reconSelector_dictLN_vectorlEReconEventcOallocatorlEReconEventgRsPgR.tagnum = -1 ;
  G__reconSelector_dictLN_reverse_iteratorlEvectorlEReconEventcOallocatorlEReconEventgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__reconSelector_dictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__reconSelector_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablereconSelector_dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_TClass);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_TObject);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_vectorlEfloatcOallocatorlEfloatgRsPgR);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_vectorlEboolcOallocatorlEboolgRsPgR);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_string);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_TList);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_TFile);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_TTree);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_TBranch);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_TSelector);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_TProofOutputFile);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_G4DSHitData);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_ReconEvent);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_TRint);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_reconSelector),sizeof(reconSelector),-1,29952,(char*)NULL,G__setup_memvarreconSelector,G__setup_memfuncreconSelector);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_vectorlEReconEventcOallocatorlEReconEventgRsPgR);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_reverse_iteratorlEvectorlEReconEventcOallocatorlEReconEventgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__reconSelector_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupreconSelector_dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupreconSelector_dict()");
  G__set_cpp_environmentreconSelector_dict();
  G__cpp_setup_tagtablereconSelector_dict();

  G__cpp_setup_inheritancereconSelector_dict();

  G__cpp_setup_typetablereconSelector_dict();

  G__cpp_setup_memvarreconSelector_dict();

  G__cpp_setup_memfuncreconSelector_dict();
  G__cpp_setup_globalreconSelector_dict();
  G__cpp_setup_funcreconSelector_dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncreconSelector_dict();
  return;
}
class G__cpp_setup_initreconSelector_dict {
  public:
    G__cpp_setup_initreconSelector_dict() { G__add_setup_func("reconSelector_dict",(G__incsetup)(&G__cpp_setupreconSelector_dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initreconSelector_dict() { G__remove_setup_func("reconSelector_dict"); }
};
G__cpp_setup_initreconSelector_dict G__cpp_setup_initializerreconSelector_dict;

